/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sptech.projeto.encapsulamento;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class TelaAluno extends javax.swing.JFrame {
Aluno aluno1= new Aluno("123", "Giuliana", "ADS");
    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloAluno1 = new javax.swing.JLabel();
        txtNota1Aluno1 = new javax.swing.JTextField();
        txtNota2Aluno1 = new javax.swing.JTextField();
        btnVerificaAprovacaoAluno1 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTituloAluno1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAluno1.setText("Aluno1");

        txtNota2Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2Aluno1ActionPerformed(evt);
            }
        });

        btnVerificaAprovacaoAluno1.setText("Verificar Aprovação");
        btnVerificaAprovacaoAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaAprovacaoAluno1ActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblResultado.setText("        ---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(lblTituloAluno1)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNota2Aluno1)
                    .addComponent(txtNota1Aluno1)
                    .addComponent(btnVerificaAprovacaoAluno1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTituloAluno1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNota1Aluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtNota2Aluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnVerificaAprovacaoAluno1)
                .addGap(32, 32, 32)
                .addComponent(lblResultado)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificaAprovacaoAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaAprovacaoAluno1ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText("potato");
        Double nota1Digitada = Double.valueOf(txtNota1Aluno1.getText());
        Double nota2Digitada = Double.valueOf(txtNota2Aluno1.getText());
        
        aluno1.setNota1(nota1Digitada);
        aluno1.setNota2(nota2Digitada);
        
//        aluno1.getMedia();;
        
        if (aluno1.isAprovado()) {
            lblResultado.setText("Aluno Passou ");
            lblResultado.setForeground(Color.GREEN);
        } else {
            lblResultado.setText("Não passou ");
            lblResultado.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnVerificaAprovacaoAluno1ActionPerformed

    private void txtNota2Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2Aluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2Aluno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificaAprovacaoAluno1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTituloAluno1;
    private javax.swing.JTextField txtNota1Aluno1;
    private javax.swing.JTextField txtNota2Aluno1;
    // End of variables declaration//GEN-END:variables
}
